# 定义触发action条件
on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # Check out the repository content
      - name: Checkout repository
        uses: actions/checkout@v4

      # setup python
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: x64
          cache: "pip" # 缓存pip依赖
          # 依赖文件路径，用于检测依赖是否有更新
          cache-dependency-path: |
            **/requirements*.txt 

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build python script into a stand-alone exe
      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true

      # Uploads artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: huobiBuyNewCoin-${{ matrix.os }}-x64
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
          include-hidden-files: true


